package com.codecool.shop.controller;

import com.codecool.shop.Utils;
import com.codecool.shop.dao.ProductCategoryDao;
import com.codecool.shop.dao.implementation.Db.ProductCategoryDaoJdbc;
import com.codecool.shop.dao.implementation.Db.SupplierDaoJdbc;
import com.codecool.shop.dao.implementation.Mem.ProductCategoryDaoMem;
import com.codecool.shop.dao.implementation.Mem.ProductDaoMem;
import com.codecool.shop.model.*;
import spark.Request;
import spark.Response;

import java.util.*;

/**
 * Product controller class is responsible to handle server client communication releted to sessions. Also responsible for
 * populating, updating and query for the different stages of orders.
 * @author Team Lava
 */
public class ProductController {

    /**
     * Render products method is responsible for populating the template generated by thymeleaf.
     * @param req request sent from client side
     * @param res response sent after processing the request
     * @return Renders the page, with the populated data
     */
    public static String renderProducts(Request req, Response res) {
        UserController.ensureUserIsLoggedIn(req, res);
        ProductCategoryDao productCategoryDataStore = ProductCategoryDaoMem.getInstance();
        SupplierDaoJdbc supplierDataStore = SupplierDaoJdbc.getInstance();

        int supplierId = 1;
        Supplier targetSupplier = supplierDataStore.find(supplierId);
        List products = targetSupplier.getProducts();

        List<Map> productsResponse = ModelBuilder.productModel(products);

        Map<String, Object> data = new HashMap<>();
        data.put("username", req.session().attribute("username"));
        data.put("categories", productCategoryDataStore.getAll());
        data.put("suppliers", supplierDataStore.getAll());
        data.put("collectionName", targetSupplier.getName());
        data.put("collection", productsResponse);

        return Utils.renderTemplate(data, "product/index");
    }


    /**
     * This method is responsible for gethering all products filtered by supplier and returns as it is
     * convertible to JSON format.
     * @param request request sent from client side
     * @param response response sent after processing the request
     * @return the jasonified list of products filtered by supplier
     */
    public static String getProductsBySupplier(Request request, Response response) {
        int supplierId = Integer.parseInt(request.params("id"));
        SupplierDaoJdbc supplierDataStore = SupplierDaoJdbc.getInstance();
        Supplier targetSupplier = supplierDataStore.find(supplierId);
        List<Product> products = targetSupplier.getProducts();

        List<Map> collection = ModelBuilder.productModel(products);

        Map<String, Object> data = new HashMap<>();
        data.put("collection", collection);
        data.put("collectionName", targetSupplier.getName());

        return Utils.toJson(data);
    }

    /**
     * This method is responsible for gethering all products filtered by category and returns as it is
     * convertible to JSON format.
     * @param request request sent from client side
     * @param response response sent after processing the request
     * @return the jasonified list of products filtered by category
     */
    public static String getProductsByCategory(Request request, Response response) {
        int categoryId = Integer.parseInt(request.params("id"));
        ProductCategoryDao productCategoryDataStore = ProductCategoryDaoJdbc.getInstance();
        ProductCategory targetCategory = productCategoryDataStore.find(categoryId);
        List<Product> products = targetCategory.getProducts();

        List<Map> collection = ModelBuilder.productModel(products);

        Map<String, Object> data = new HashMap<>();
        data.put("collection", collection);
        data.put("collectionName", targetCategory.getName());

        return Utils.toJson(data);
    }

    /**
     * This method is responsible to create a lineitem object that will represent the actual item object in an
     * orderable format
     * @param req request sent from client side
     * @param res response sent after processing the request
     * @return Returns a map with all the lineitems in the sopping cart completed with the newly item in the cart
     */
    public static String handleOrder(Request req, Response res) {
        int productId = Integer.parseInt(req.params("id"));
        Product targetItem = ProductDaoMem.getInstance().find(productId);
        if (!isLineItem(targetItem)) {
            LineItem newLineItem = new LineItem(targetItem, targetItem.getDefaultPrice());
            Order.getCurrentOrder().add(newLineItem);
        }

        Map<String, Object> response = getShoppingCartData();
        return Utils.toJson(response);
    }

    /**
     * This method is responsible for adding user data to the order.
     * @param request request sent from client side
     * @param response response sent after processing the request
     * @return a confirmation that the update for the order has been processed
     */
    public static String addUserData(Request request, Response response) {
        Map<String, String> userData = Utils.parseJson(request);

        Order.getCurrentOrder().setUserData(userData);

        String res = "order updated with user data";
        return Utils.toJson(res);
    }

    /**
     * This method is responsible for adding payment data to the order.
     * @param request request sent from client side
     * @param response response sent after processing the request
     * @return a confirmation that the update for the order has been processed
     */
    public static String addPaymentData(Request request, Response response) {
        Map<String, String> userData = Utils.parseJson(request);
        Order.getCurrentOrder().setPaymentData(userData);

        String res = "order updated with payment data";
        new Order();
        return Utils.toJson(res);
    }

    /**
     * This method is responsible to check if the argument item is a lineitem ready to be processed as a
     * shopping cart item.
     * @param targetItem
     * @return gives the state of the argument item
     */
    private static boolean isLineItem(Product targetItem) {
        for (LineItem lineItem : Order.getCurrentOrder().getAddedItems()) {
            if (lineItem.getItem().equals(targetItem)) {
                lineItem.incrementQuantity();
                return true;
            }
        }
        return false;
    }

    /**
     * This method is responsible to update the desired quantity of a lineitem of interest upon request
     * @param req request sent from client side
     * @param res response sent after processing the request
     * @return updated sopping cart data in a jasonified format
     */
    public static String changeQuantity(Request req, Response res) {
        Map<String, String> data = Utils.parseJson(req);
        List<LineItem> lineItems = Order.getCurrentOrder().getAddedItems();
        LineItem targetLineItem = null;
        for (LineItem lineItem : lineItems) {
            if (lineItem.getItem().getId() == Integer.parseInt(data.get("Id"))) {
                targetLineItem = lineItem;
                break;
            }
        }
        if (Objects.equals(data.get("change"), "plus")) {
            if (targetLineItem != null) {
                targetLineItem.incrementQuantity();
            }
            Order.getCurrentOrder().changeTotalPrice();
        } else {
            if (targetLineItem != null && targetLineItem.getQuantity() > 0) {
                targetLineItem.decrementQuantity();
                if (targetLineItem.getQuantity() == 0) {
                    Order.getCurrentOrder().getAddedItems().remove(targetLineItem);
                }

            }
            Order.getCurrentOrder().changeTotalPrice();
        }
        Map<String, Object> response = getShoppingCartData();
        return Utils.toJson(response);
    }

    /**
     * This method gethers all possible data about the shopping cart.
     * @return a map with all the fields of the shopping cart for further processing
     */
    private static Map<String, Object> getShoppingCartData() {
        List<LineItem> orderItems = Order.getCurrentOrder().getAddedItems();
        List<Map> orders = ModelBuilder.lineItemModel(orderItems);
        Map<String, Object> response = new HashMap<>();
        response.put("itemsNumber", Integer.toString(Order.getCurrentOrder().getTotalSize()));
        response.put("totalPrice", Float.toString(Order.getCurrentOrder().getTotalPrice()));
        response.put("shoppingCart", orders);

        return response;
    }
}
